/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.spring;

import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

import com.spring.controller.MovieController;

public class MovieApp {
    

    public static void main(String[] args) {
    	
    	ApplicationContext context = new ClassPathXmlApplicationContext("beans.xml");
    	
    	MovieController controller = context.getBean("movieController",MovieController.class);
    	
    	System.out.println(controller.getMovie().getName());
    }
    
    
}
