/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.spring;

import java.util.Properties;

import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.context.annotation.Bean;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSenderImpl;

import com.spring.mail.SimpleMailSender;

@SpringBootApplication
public class App {

	public static void main(String[] args) {

		ApplicationContext context = new AnnotationConfigApplicationContext(App.class);

		SimpleMailSender s = context.getBean(SimpleMailSender.class);

		s.sendMail();

	}

	@Bean
	public JavaMailSenderImpl getMailSender() {
		
		Properties props = new Properties();
		props.put("mail.smtp.auth", "true");
		props.put("mail.smtp.starttls.enable", "true");
		props.put("mail.smtp.host", "smtp.gmail.com");
		props.put("mail.smtp.port", "587");
		
		JavaMailSenderImpl javaMailSenderImpl = new JavaMailSenderImpl();
		String host = "smtp.gmail.com";
		javaMailSenderImpl.setHost(host);
		javaMailSenderImpl.setPort(587);
		javaMailSenderImpl.setJavaMailProperties(props);
		javaMailSenderImpl.setUsername("beargrylls@gmail.com");
		javaMailSenderImpl.setPassword("*******");
		
		return javaMailSenderImpl;
	}
	
	@Bean
	public SimpleMailMessage getSimpleMailMessage() {
		SimpleMailMessage simpleMailMessage = new SimpleMailMessage();
		
		String subject = "Test";
		simpleMailMessage.setSubject(subject);
	
		
		return simpleMailMessage;
	}
	
	
}
