
package com.spring;

import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

import com.spring.controller.AppController;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class ProfileApp {

	public static void main(String... args) {

		AnnotationConfigApplicationContext contexst = new AnnotationConfigApplicationContext();
		
		//set context profile
		contexst.getEnvironment().setActiveProfiles("prod");
		contexst.register(DevConfig.class,ProdConfig.class);
		contexst.refresh();
		
		AppController controller = contexst.getBean(AppController.class);
		
		System.out.println(controller.getAppDetails().getName());
		
		
	}

}
