/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.spring.test;


import org.junit.Test;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        
    }
}
