package com.spring;

import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

import com.spring.beans.ReadProps;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

	public static void main(String... strings) {
		ApplicationContext context = new ClassPathXmlApplicationContext("beans.xml");

		ReadProps props = context.getBean("postTest", ReadProps.class);

		System.out.println(props.getClassName() + " : is the class :" + props.getName());
	}

}
